/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import model.Account;
import model.Addr;
import model.Demo;
import model.Driving;
import model.Medical;

/**
 *
 * @author Harsh
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Demo demo;//Object creation
    Addr addr;
    Driving driving;
    Medical medical;
    Account account;

    
    public MainJFrame() {
        initComponents();
        demo = new Demo();//Intialise object
        addr = new Addr();
        driving = new Driving();
        medical = new Medical();
        account = new Account();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnDemoCreate = new javax.swing.JButton();
        btnGenReport = new javax.swing.JButton();
        btnDemoView = new javax.swing.JButton();
        btnAddrCreate = new javax.swing.JButton();
        btnAddrView = new javax.swing.JButton();
        btnAccountCreate = new javax.swing.JButton();
        btnAccountView = new javax.swing.JButton();
        btnDrivingCreate = new javax.swing.JButton();
        btnDrivingView = new javax.swing.JButton();
        btnMedicalCreate = new javax.swing.JButton();
        btnMedicalView = new javax.swing.JButton();
        lblDemo = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        lblDriving = new javax.swing.JLabel();
        lblMedical = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        Forms = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(51, 51, 51));
        controlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        controlPanel.setToolTipText("");

        btnDemoCreate.setText("Create");
        btnDemoCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDemoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoCreateActionPerformed(evt);
            }
        });

        btnGenReport.setBackground(new java.awt.Color(153, 255, 153));
        btnGenReport.setText("Generate Report");
        btnGenReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenReport.setPreferredSize(new java.awt.Dimension(65, 23));
        btnGenReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenReportActionPerformed(evt);
            }
        });

        btnDemoView.setText("View");
        btnDemoView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDemoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoViewActionPerformed(evt);
            }
        });

        btnAddrCreate.setText("Create");
        btnAddrCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddrCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddrCreateActionPerformed(evt);
            }
        });

        btnAddrView.setText("View");
        btnAddrView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddrView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddrViewActionPerformed(evt);
            }
        });

        btnAccountCreate.setText("Create");
        btnAccountCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccountCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountCreateActionPerformed(evt);
            }
        });

        btnAccountView.setText("View");
        btnAccountView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccountView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountViewActionPerformed(evt);
            }
        });

        btnDrivingCreate.setText("Create");
        btnDrivingCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrivingCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrivingCreateActionPerformed(evt);
            }
        });

        btnDrivingView.setText("View");
        btnDrivingView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDrivingView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrivingViewActionPerformed(evt);
            }
        });

        btnMedicalCreate.setText("Create");
        btnMedicalCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicalCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalCreateActionPerformed(evt);
            }
        });

        btnMedicalView.setText("View");
        btnMedicalView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicalView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalViewActionPerformed(evt);
            }
        });

        lblDemo.setForeground(new java.awt.Color(255, 255, 255));
        lblDemo.setText("Demographic Information:");

        lblAddr.setForeground(new java.awt.Color(255, 255, 255));
        lblAddr.setText("Address Information:");

        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setText("Account Information:");

        lblDriving.setForeground(new java.awt.Color(255, 255, 255));
        lblDriving.setText("Driver's License Information:");

        lblMedical.setForeground(new java.awt.Color(255, 255, 255));
        lblMedical.setText("Medical record:");

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Please select from the menu below");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblHeader)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenReport, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAddr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDriving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDemoCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAccountCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDrivingCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(btnMedicalCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(btnAddrCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAddrView, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAccountView, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDrivingView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMedicalView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDemoView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDemoCreate)
                    .addComponent(btnDemoView)
                    .addComponent(lblDemo))
                .addGap(31, 31, 31)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddrCreate)
                    .addComponent(btnAddrView)
                    .addComponent(lblAddr))
                .addGap(31, 31, 31)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccountCreate)
                    .addComponent(btnAccountView)
                    .addComponent(lblAccount))
                .addGap(31, 31, 31)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDrivingCreate)
                    .addComponent(btnDrivingView)
                    .addComponent(lblDriving))
                .addGap(31, 31, 31)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMedicalCreate)
                    .addComponent(btnMedicalView)
                    .addComponent(lblMedical))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnGenReport, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        SplitPane.setLeftComponent(controlPanel);

        Forms.setBackground(new java.awt.Color(204, 255, 255));
        Forms.setPreferredSize(new java.awt.Dimension(397, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Please select from the menu on the left");

        javax.swing.GroupLayout FormsLayout = new javax.swing.GroupLayout(Forms);
        Forms.setLayout(FormsLayout);
        FormsLayout.setHorizontalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormsLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        FormsLayout.setVerticalGroup(
            FormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormsLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        SplitPane.setRightComponent(Forms);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenReportActionPerformed
        // TODO add your handling code here:
        ReportView reportview = new ReportView (demo,addr,account,driving,medical);
        SplitPane.setRightComponent(reportview);
    }//GEN-LAST:event_btnGenReportActionPerformed

    private void btnDemoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoViewActionPerformed
        // TODO add your handling code here:
        DemoView demoview = new DemoView (demo);
        SplitPane.setRightComponent(demoview);
    }//GEN-LAST:event_btnDemoViewActionPerformed

    private void btnDemoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoCreateActionPerformed
        // TODO add your handling code here:
        DemoCreate democreate = new DemoCreate (demo);
        SplitPane.setRightComponent(democreate);
    }//GEN-LAST:event_btnDemoCreateActionPerformed

    private void btnAddrCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddrCreateActionPerformed
        // TODO add your handling code here:
        AddrCreate addrcreate = new AddrCreate (addr);
        SplitPane.setRightComponent(addrcreate);
    }//GEN-LAST:event_btnAddrCreateActionPerformed

    private void btnAddrViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddrViewActionPerformed
        // TODO add your handling code here:
        AddrView addrview = new AddrView (addr);
        SplitPane.setRightComponent(addrview);
    }//GEN-LAST:event_btnAddrViewActionPerformed

    private void btnAccountCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountCreateActionPerformed
        // TODO add your handling code here:
        AccountCreate accountcreate = new AccountCreate (account);
        SplitPane.setRightComponent(accountcreate);
    }//GEN-LAST:event_btnAccountCreateActionPerformed

    private void btnAccountViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountViewActionPerformed
        // TODO add your handling code here:
        AccountView accountview = new AccountView (account);
        SplitPane.setRightComponent(accountview);
    }//GEN-LAST:event_btnAccountViewActionPerformed

    private void btnDrivingCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrivingCreateActionPerformed
        // TODO add your handling code here:
        DrivingCreate drivingcreate = new DrivingCreate (driving);
        SplitPane.setRightComponent(drivingcreate);
    }//GEN-LAST:event_btnDrivingCreateActionPerformed

    private void btnDrivingViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrivingViewActionPerformed
        // TODO add your handling code here:
        DrivingView drivingview = new DrivingView (driving);
        SplitPane.setRightComponent(drivingview);
    }//GEN-LAST:event_btnDrivingViewActionPerformed

    private void btnMedicalCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalCreateActionPerformed
        // TODO add your handling code here:
        MedicalCreate medicalcreate = new MedicalCreate (medical);
        SplitPane.setRightComponent(medicalcreate);
    }//GEN-LAST:event_btnMedicalCreateActionPerformed

    private void btnMedicalViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalViewActionPerformed
        // TODO add your handling code here:
        MedicalView medicalview = new MedicalView (medical);
        SplitPane.setRightComponent(medicalview);
    }//GEN-LAST:event_btnMedicalViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Forms;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnAccountCreate;
    private javax.swing.JButton btnAccountView;
    private javax.swing.JButton btnAddrCreate;
    private javax.swing.JButton btnAddrView;
    private javax.swing.JButton btnDemoCreate;
    private javax.swing.JButton btnDemoView;
    private javax.swing.JButton btnDrivingCreate;
    private javax.swing.JButton btnDrivingView;
    private javax.swing.JButton btnGenReport;
    private javax.swing.JButton btnMedicalCreate;
    private javax.swing.JButton btnMedicalView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblDemo;
    private javax.swing.JLabel lblDriving;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblMedical;
    // End of variables declaration//GEN-END:variables
}
