/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import model.Account;
import model.Addr;
import model.Demo;
import model.Driving;
import model.Medical;

/**
 *
 * @author Harsh
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    Demo demo;
    Account account;
    Addr addr; 
    Driving driving;
    Medical medical;
    
    
    public ReportView(Demo demo, Addr addr, Account account, Driving driving, Medical medical) {
        initComponents();
        this.demo = demo;
        this.addr = addr;
        this.account = account;
        this.driving = driving;
        this.medical = medical;
        display();
        
        
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDemographics = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        lblDriverLic = new javax.swing.JLabel();
        lblMedRec = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtStreetAddr = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        txtBankRoutNo = new javax.swing.JTextField();
        txtBankAccNo = new javax.swing.JTextField();
        txtAccBal = new javax.swing.JTextField();
        txtAccType = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtDateOfIssue = new javax.swing.JTextField();
        txtDateOfExpiraion = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        txtMedicalRecNo = new javax.swing.JTextField();
        txtAllergy1 = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        txtAllergy3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblStreetAddr = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        lblAccBal = new javax.swing.JLabel();
        lblBankAccNo = new javax.swing.JLabel();
        lblBankRoutNo = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblDateOfIssue = new javax.swing.JLabel();
        lblDateOfExpiration = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        lblLicenseNo = new javax.swing.JLabel();
        lblMedicalRecNo = new javax.swing.JLabel();
        lblAllergy1 = new javax.swing.JLabel();
        lblAllergy2 = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        lblDemographics.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblDemographics.setText("Demographics");

        lblAddress.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblAddress.setText("Address");

        lblAccount.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblAccount.setText("Bank Account");

        lblDriverLic.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblDriverLic.setText("Driver's License");

        lblMedRec.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblMedRec.setText("Medical Record");

        txtFname.setEditable(false);
        txtFname.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtLname.setEditable(false);
        txtLname.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtPhoneNo.setEditable(false);
        txtPhoneNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtDOB.setEditable(false);
        txtDOB.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtHeight.setEditable(false);
        txtHeight.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtWeight.setEditable(false);
        txtWeight.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtSSN.setEditable(false);
        txtSSN.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtStreetAddr.setEditable(false);
        txtStreetAddr.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtCity.setEditable(false);
        txtCity.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtState.setEditable(false);
        txtState.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtZipCode.setEditable(false);
        txtZipCode.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtBankName.setEditable(false);
        txtBankName.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });

        txtBankRoutNo.setEditable(false);
        txtBankRoutNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtBankAccNo.setEditable(false);
        txtBankAccNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtBankAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccNoActionPerformed(evt);
            }
        });

        txtAccBal.setEditable(false);
        txtAccBal.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtAccType.setEditable(false);
        txtAccType.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtAccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccTypeActionPerformed(evt);
            }
        });

        txtLicenseNumber.setEditable(false);
        txtLicenseNumber.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });

        txtDateOfIssue.setEditable(false);
        txtDateOfIssue.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtDateOfIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfIssueActionPerformed(evt);
            }
        });

        txtDateOfExpiraion.setEditable(false);
        txtDateOfExpiraion.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtBloodType.setEditable(false);
        txtBloodType.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtMedicalRecNo.setEditable(false);
        txtMedicalRecNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtMedicalRecNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecNoActionPerformed(evt);
            }
        });

        txtAllergy1.setEditable(false);
        txtAllergy1.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        txtAllergy2.setEditable(false);
        txtAllergy2.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        txtAllergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergy2ActionPerformed(evt);
            }
        });

        txtAllergy3.setEditable(false);
        txtAllergy3.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Report:");

        lblDOB.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblDOB.setText("Date of Birth:");

        lblFname.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblFname.setText("First Name:");

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblAge.setText("Age:");

        lblHeight.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblHeight.setText("Height:");

        lblWeight.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblWeight.setText("Weight:");

        lblSSN.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblSSN.setText("SSN:");

        lblLname.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblLname.setText("Last Name:");

        lblPhoneNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblPhoneNo.setText("Phone Number:");

        lblState.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblState.setText("State:");

        lblZipCode.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblZipCode.setText("Zip Code:");

        lblStreetAddr.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblStreetAddr.setText("Street:");

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblCity.setText("City:");

        lblAccType.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblAccType.setText("Account Type:");

        lblAccBal.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblAccBal.setText("Account Balance:");

        lblBankAccNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblBankAccNo.setText("Bank Account No:");

        lblBankRoutNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblBankRoutNo.setText("Bank Routing No:");

        lblBankName.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblBankName.setText("Bank Name:");

        lblDateOfIssue.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblDateOfIssue.setText("Date of Issue:");

        lblDateOfExpiration.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblDateOfExpiration.setText("Date of Expiration:");

        lblBloodType.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblBloodType.setText("Blood Type:");

        lblLicenseNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblLicenseNo.setText("License Number:");

        lblMedicalRecNo.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblMedicalRecNo.setText("Record No:");

        lblAllergy1.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblAllergy1.setText("Allergy 1:");

        lblAllergy2.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblAllergy2.setText("Allergy 2:");

        lblAllergy3.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblAllergy3.setText("Allergy 3:");

        lblImg.setFont(new java.awt.Font("Tahoma", 0, 7)); // NOI18N
        lblImg.setText("Image:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtWeight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHeight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDOB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblDemographics, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDriverLic, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblBloodType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDateOfExpiration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLicenseNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDateOfIssue)
                                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLicenseNumber)
                                        .addComponent(txtDateOfExpiraion)
                                        .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblStreetAddr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtStreetAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMedicalRecNo)
                                                    .addComponent(lblAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtMedicalRecNo, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                    .addComponent(txtZipCode)
                                                    .addComponent(txtAllergy1)
                                                    .addComponent(txtAllergy2)
                                                    .addComponent(txtAllergy3)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblBankRoutNo)
                                                    .addComponent(lblAccBal)
                                                    .addComponent(lblAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblBankName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtBankRoutNo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                    .addComponent(txtAccBal)
                                                    .addComponent(txtAccType, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtBankAccNo)
                                                    .addComponent(txtBankName)))
                                            .addComponent(lblAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblAllergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankName)
                            .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankAccNo)
                            .addComponent(txtBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBankRoutNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBankRoutNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccBal)
                            .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccType)
                            .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStreetAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStreetAddr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipCode))
                        .addGap(18, 18, 18)
                        .addComponent(lblMedRec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedicalRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAllergy1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDemographics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFname))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNo)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeight))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDriverLic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicenseNo)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateOfIssue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateOfExpiraion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateOfExpiration)
                            .addComponent(lblMedicalRecNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBloodType))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAllergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAllergy2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAllergy3)
                            .addComponent(txtAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImg))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtBankAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccNoActionPerformed

    private void txtAccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccTypeActionPerformed

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtAllergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergy2ActionPerformed

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void txtDateOfIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfIssueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfIssueActionPerformed

    private void txtMedicalRecNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccBal;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblBankAccNo;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankRoutNo;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDateOfExpiration;
    private javax.swing.JLabel lblDateOfIssue;
    private javax.swing.JLabel lblDemographics;
    private javax.swing.JLabel lblDriverLic;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblMedRec;
    private javax.swing.JLabel lblMedicalRecNo;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAddr;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccType;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtBankAccNo;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtBankRoutNo;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDateOfExpiraion;
    private javax.swing.JTextField txtDateOfIssue;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMedicalRecNo;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddr;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void display() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          //Demo
          txtFname.setText(demo.getFirstName());
          txtLname.setText(demo.getLastName());
          txtPhoneNo.setText(demo.getPhoneNo());
          txtDOB.setText(demo.getDob());
          txtAge.setText(demo.getAge());
          txtHeight.setText(demo.getHeight());
          txtWeight.setText(demo.getWeight());
          txtSSN.setText(demo.getSsn());
          //Addr
          txtStreetAddr.setText(addr.getStreetAddr());
          txtCity.setText(addr.getCity());
          txtState.setText(addr.getState());
          txtZipCode.setText(addr.getZipCode());
          //Account
          txtBankName.setText(account.getBankName());
          txtBankRoutNo.setText(account.getBankRouting());
          txtBankAccNo.setText(account.getBankAccountNo());
          txtAccBal.setText(account.getAccountBal());
          txtAccType.setText(account.getAccountType());
          //Driving
          txtLicenseNumber.setText(driving.getLicenseNo());
          txtDateOfIssue.setText(driving.getDateIssue());
          txtDateOfExpiraion.setText(driving.getDateExpiry());
          txtBloodType.setText(driving.getBloodType());
          //Medical
          txtMedicalRecNo.setText(medical.getMedicalRecordNo());
          txtAllergy1.setText(medical.getAlergy1());
          txtAllergy2.setText(medical.getAlergy2());
          txtAllergy3.setText(medical.getAlergy3());
          //Image
          ImageIcon iconObj = new ImageIcon(driving.getPicture());
          lblImage.setIcon(iconObj);
    }
}
